RBMC: Reject rbmctool failovers on the active BMC
Though one can initiate a failover on the active BMC, as it's needed for
certain system error paths, the documentation and general direction is
to always initiate one on the passive BMC.

To keep in the spirit of that, only let someone use the 'rbmctool
--failover' from the passive BMC.  If the system is in a state to do a
failover, then the passive BMC would need to be healthy anyway.

If someone really wants to, they can use the busctl command to start one
on the active BMC.

Tested:
```
$ rbmctool --failover
Error: rbmctool only allows starting a failover on the passive BMC
```

Change-Id: Iba3870b9df355e063194ea13206b017889e04f4e
Signed-off-by: Matt Spinler <spinler@us.ibm.com>